server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/product_service_dev_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
